# scheduler

Update the alias command:

1.  Navigate to ~/.bashrc
2.  Add: alias schedule='python Schedular/todoist.py'

# Debugging

Issue: day_order was set to -1 for newly entered Todoist tasks Solution: I'm
fairly confident that this is a glich on Todoist's end. What I did was move
around one of the newly entered tasks in the 'today' view.
